esphome:
  name: ld2451-validate
  friendly_name: LD2451 Validate

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  platform: esphome

wifi:
  ssid: "test"
  password: "testtest"

external_components:
  - source:
      type: local
      path: ../../components
    components: [ld2451]

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

ld2451:
  id: radar
  uart_id: uart_bus
  max_distance: 100
  min_distance: 5
  min_speed: 10
  detection_direction: both
  no_target_delay: 2
  trigger_count: 2
  min_snr: 4
  speed_correction: 1.10
  target_count:
    name: "LD2451 Target Count"
  vehicle_detected:
    name: "LD2451 Vehicle Detected"
  angle:
    name: "LD2451 Angle"
  distance:
    name: "LD2451 Distance"
  speed:
    name: "LD2451 Speed"
  snr:
    name: "LD2451 SNR"
  direction:
    name: "LD2451 Direction"
