esphome:
  name: ld2451-validate
  friendly_name: LD2451 Validate

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  platform: esphome

wifi:
  ssid: "test"
  password: "testtest"

external_components:
  - source:
      type: local
      path: ../../components
    components: [ld2451]

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

ld2451:
  id: radar
  uart_id: uart_bus
  target_count:
    name: "LD2451 Target Count"
  vehicle_detected:
    name: "LD2451 Vehicle Detected"
  angle:
    name: "LD2451 Angle"
  distance:
    name: "LD2451 Distance"
  speed:
    name: "LD2451 Speed"
  speed_mph:
    name: "LD2451 Speed MPH"
  snr:
    name: "LD2451 SNR"
  direction:
    name: "LD2451 Direction"
  target_1_angle:
    name: "LD2451 Target 1 Angle"
  target_1_x:
    name: "LD2451 Target 1 X"
  target_1_y:
    name: "LD2451 Target 1 Y"
  target_1_distance:
    name: "LD2451 Target 1 Distance"
  target_1_speed:
    name: "LD2451 Target 1 Speed"
  target_1_speed_mph:
    name: "LD2451 Target 1 Speed MPH"
  target_1_snr:
    name: "LD2451 Target 1 SNR"
  target_1_direction:
    name: "LD2451 Target 1 Direction"
  target_2_angle:
    name: "LD2451 Target 2 Angle"
  target_2_x:
    name: "LD2451 Target 2 X"
  target_2_y:
    name: "LD2451 Target 2 Y"
  target_2_distance:
    name: "LD2451 Target 2 Distance"
  target_2_speed:
    name: "LD2451 Target 2 Speed"
  target_2_speed_mph:
    name: "LD2451 Target 2 Speed MPH"
  target_2_snr:
    name: "LD2451 Target 2 SNR"
  target_2_direction:
    name: "LD2451 Target 2 Direction"
  target_3_angle:
    name: "LD2451 Target 3 Angle"
  target_3_x:
    name: "LD2451 Target 3 X"
  target_3_y:
    name: "LD2451 Target 3 Y"
  target_3_distance:
    name: "LD2451 Target 3 Distance"
  target_3_speed:
    name: "LD2451 Target 3 Speed"
  target_3_speed_mph:
    name: "LD2451 Target 3 Speed MPH"
  target_3_snr:
    name: "LD2451 Target 3 SNR"
  target_3_direction:
    name: "LD2451 Target 3 Direction"
